### ISSUE TITLE
Memory system

### ISSUE THREAD

**Issue by kalDima1218** [none-None1/BFFuck#1]
Hi! How do you implement a memory storage system? I mean how variables are accessed from different parts of the program

**Comment by none-None1** [comment]
Hi! Thanks for asking! 'tis like this: BFFuck divides the tape into two parts: The registers (`playfield`) and the memory (where the variables are stored). BFFuck keeps a dictionary `valdict`, that maps variables to their position in the tape. The registers are used as temporary values for operating brainfuck algorithms. Also, BFFuck simulates the memory pointer and uses the function `movptr` to generate brainfuck code that moves memory pointer to a position.

**Comment by kalDima1218** [comment]
Thanks for explanation!
