### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by kalDima1218** [none-None1/BFFuck#2]
Hi, I was thinking about memory management, like C++: arrays, pointers (which I think is naturally necessary when working with arrays). It seems to me that this will greatly expand the possibilities of writing complex algorithms. But i haven't any idea how to store and dereference it. I have idea something like hash table (you reserving some space at the beginning of the memory and making it 2x more if it is necessary with shifting all data), but i think it is overkill. What do you think?

**Comment by none-None1** [comment]
Yes, you're right. But the largest problem is: BFFuck integers are only bytes, that means only the first 256 addresses can be accessed by addresses. Also, the code is getting messier, making it harder to add new features.

**Comment by kalDima1218** [comment]
I was thinking about wide integers (simply you use 4 cells instead of 1) but not obvious how to do it (+-1 will be much harder to implement). Also, do you have any idea about recursion? I think it will let to write complex algorithms (like fft or some divide and conquer)

**Comment by none-None1** [comment]
On [esolang](https://esolangs.org/wiki/Brainfuck_bitwidth_conversions), there seems to be a method to deal with wide integers. But recursion may be difficult, as BFFuck doesn't support jumps.

**Comment by none-None1** [comment]
I'm planning [this](https://github.com/none-None1/BFFuck/issues/4) for the future

**Comment by none-None1** [comment]
Thanks for your advice, I've implemented wide integers and pointers!
